configurar variaveis para deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -72,4 +72,97 @@ jobs:
       run: |
         echo "Coverage Percentage: ${{ steps.coverage.outputs.coverage_percentage }}%"
 
-  ## Adicionar os passos de deploy aqui
+  deploy:
+    name: Deploy
+    runs-on: ubuntu-latest
+    needs: build
+    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+    
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
+          aws-region: ${{ vars.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+      
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v2
+      
+      - name: Build, tag, and push image to Amazon ECR
+        id: build-image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ecr-${{ vars.PROJECT_NAME }}-worker-pagamento
+          IMAGE_TAG: ${{ github.sha }}
+        run: |
+          docker build -f src/WorkerService/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+        
+      - name: Install Kubectl
+        run: |
+          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/
+
+      - name: Configure Kubectl
+        run: |
+          aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}
+      
+      - name: Create/Update Secrets
+        env:
+          DB_INSTANCE_PEDIDOS: ${{ secrets.DB_INSTANCE_PEDIDOS }}
+          DB_PASSWORD_PEDIDOS: ${{ secrets.DB_PASSWORD_PEDIDOS }}
+          DB_UID_PEDIDOS: ${{ secrets.DB_UID_PEDIDOS }}
+          DB_PORT: ${{ vars.DB_PORT }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          SECRET_NAME="worker-payment-secret"
+          CONNECTION_STRING="Server=${{ env.DB_INSTANCE_PEDIDOS }},${{ env.DB_PORT }};Database=SnackTechProductsDb;User=${{ env.DB_UID_PEDIDOS }};Password=${{ env.DB_PASSWORD_PEDIDOS }};TrustServerCertificate=True"
+      
+          if kubectl get secret "$SECRET_NAME" > /dev/null 2>&1; then
+            kubectl delete secret "$SECRET_NAME" 
+          fi
+      
+          kubectl create secret generic "$SECRET_NAME"  \
+            --from-literal=ConnectionStrings__DefaultConnection="$CONNECTION_STRING" \
+            --from-literal=AWS__AccessKey="$AWS_ACCESS_KEY_ID" \
+            --from-literal=AWS__SecretKey="$AWS_SECRET_ACCESS_KEY"
+    
+      - name: Create/Update configmap
+        env:
+          AWS_REGION: ${{ vars.AWS_REGION }} 
+          SQS_QUEUE_PAYMENT_NAME: ${{ vars.SQS_QUEUE_PAYMENT_NAME }} 
+          SQS_QUEUE_PAYMENT_DLQ_NAME: ${{ vars.SQS_QUEUE_PAYMENT_DLQ_NAME }}
+          AWS_ACCOUNT_ID_VOCLABS: ${{ secrets.AWS_ACCOUNT_ID_VOCLABS }}
+
+        run: |
+          CONFIGMAP_NAME="worker-payment-configmap" 
+
+          if kubectl get configmap "$CONFIGMAP_NAME" > /dev/null 2>&1; then
+            kubectl delete configmap "$CONFIGMAP_NAME"
+          fi
+
+          kubectl create configmap "$CONFIGMAP_NAME" \
+            --from-literal=AWS__QueueUrl="https://sqs.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ACCOUNT_ID_VOCLABS }}/${{ env.SQS_QUEUE_PAYMENT_NAME }}" \
+            --from-literal=AWS__DlqQueueURL="https://sqs.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ACCOUNT_ID_VOCLABS }}/${{ env.SQS_QUEUE_PAYMENT_DLQ_NAME }}" \
+            --from-literal=AWS__ServiceUrl="https://sqs.${{ env.AWS_REGION }}.amazonaws.com" /
+          
+      - name: Replace ECR image string value
+        env:
+          IMAGE_URI: ${{ steps.build-image.outputs.image }}
+        run: |
+          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i k8s/01-orders-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
+      
+      - name: Deploy to EKS
+        run: |
+          kubectl apply -f k8s
